### ISSUE TITLE
Implementation ~ Basics TODO

### ISSUE THREAD

**Issue by Hoediur** [winterlantern/Sentence2Bloom#1]
- [ ]  Implementation of (l,k) bracketed L system derivation routine
- [ ] implement 2D turtle 🐢 interpreter of bracketed L system
- [ ] research possible render libraries, preferably 3D compatible for easier expandability e.g. LWJGL 3.0
- [ ] experiment with different transformation routines from chomsky grammar to L System
